# Generated by Django 2.2.2 on 2019-06-27 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinnews',
            name='brief',
            field=models.CharField(max_length=120, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='chinnews',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
        migrations.CreateModel(
            name='SysNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('remark', models.CharField(blank=True, max_length=300, verbose_name='描述')),
                ('is_root', models.BooleanField(default=True, verbose_name='是否一级菜单')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, default=0, limit_choices_to={'is_delete': False, 'is_root': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.SysNav', verbose_name='父级')),
            ],
            options={
                'verbose_name': '导航菜单管理',
                'verbose_name_plural': '导航菜单管理',
                'db_table': 'sys_nav',
                'ordering': ['sort', '-create_time'],
            },
        ),
    ]
