# Generated by Django 3.0.5 on 2020-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chincompet_chincompetvideo_chinenrollcompet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysnav',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='链接'),
        ),
    ]
