# Generated by Django 2.2.2 on 2019-07-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190724_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinquestion',
            name='remark',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
