# Generated by Django 3.0.5 on 2020-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200628_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='chincompet',
            name='en_sub_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='视频标题(英文)'),
        ),
        migrations.AddField(
            model_name='chincompet',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='视频标题(中文)'),
        ),
    ]
